import type { Gender } from './family-member'

export enum RelationshipType {
  // Ascending
  PATERNAL_GRANDFATHER = 'PATERNAL_GRANDFATHER',
  PATERNAL_GRANDMOTHER = 'PATERNAL_GRANDMOTHER',
  MATERNAL_GRANDFATHER = 'MATERNAL_GRANDFATHER',
  MATERNAL_GRANDMOTHER = 'MATERNAL_GRANDMOTHER',
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  PATERNAL_UNCLE = 'PATERNAL_UNCLE',
  PATERNAL_AUNT = 'PATERNAL_AUNT',
  MATERNAL_UNCLE = 'MATERNAL_UNCLE',
  MATERNAL_AUNT = 'MATERNAL_AUNT',

  // Lateral
  OLDER_BROTHER = 'OLDER_BROTHER',
  OLDER_SISTER = 'OLDER_SISTER',
  SPOUSE = 'SPOUSE',
  YOUNGER_BROTHER = 'YOUNGER_BROTHER',
  YOUNGER_SISTER = 'YOUNGER_SISTER',
  PATERNAL_COUSIN_MALE_OLDER = 'PATERNAL_COUSIN_MALE_OLDER',
  PATERNAL_COUSIN_FEMALE_OLDER = 'PATERNAL_COUSIN_FEMALE_OLDER',
  PATERNAL_COUSIN_MALE_YOUNGER = 'PATERNAL_COUSIN_MALE_YOUNGER',
  PATERNAL_COUSIN_FEMALE_YOUNGER = 'PATERNAL_COUSIN_FEMALE_YOUNGER',
  MATERNAL_COUSIN_MALE_OLDER = 'MATERNAL_COUSIN_MALE_OLDER',
  MATERNAL_COUSIN_FEMALE_OLDER = 'MATERNAL_COUSIN_FEMALE_OLDER',
  MATERNAL_COUSIN_MALE_YOUNGER = 'MATERNAL_COUSIN_MALE_YOUNGER',
  MATERNAL_COUSIN_FEMALE_YOUNGER = 'MATERNAL_COUSIN_FEMALE_YOUNGER',

  // Descending (children)
  SON = 'SON',
  DAUGHTER = 'DAUGHTER',
  NEPHEW = 'NEPHEW',
  NIECE = 'NIECE',

  // Descending (grandchildren)
  GRANDSON = 'GRANDSON',
  GRANDDAUGHTER = 'GRANDDAUGHTER',

  // Descending (great-grandchildren)
  GREAT_GRANDSON = 'GREAT_GRANDSON',
  GREAT_GRANDDAUGHTER = 'GREAT_GRANDDAUGHTER',

  // Ascending (great-grandparents)
  PATERNAL_GREAT_GRANDFATHER = 'PATERNAL_GREAT_GRANDFATHER',
  PATERNAL_GREAT_GRANDMOTHER = 'PATERNAL_GREAT_GRANDMOTHER',
  MATERNAL_GREAT_GRANDFATHER = 'MATERNAL_GREAT_GRANDFATHER',
  MATERNAL_GREAT_GRANDMOTHER = 'MATERNAL_GREAT_GRANDMOTHER',
}

export type RelationshipKey = `${Gender}:${RelationshipType}`

export type RelationshipMapping = Record<RelationshipKey, import('./kinship-term').KinshipTerm>
